# Version
version: '3.8'

services:
  os:
    container_name: os_kalilinux
    build:
      context: ./
      dockerfile: docker/os.dockerfile
    command: bash
    tty: true
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
    ports:
        - "1993:1993"
    volumes:
      - /tmp/.X11-unix/os_kalilinux:/tmp/.X11-unix
      - ./docker/deb9.list:/etc/apt/sources.list.d/deb9.list
    cpuset: 0,1,2,3
    mem_reservation: 512m
    mem_limit: 4GB